labels: ["product/editor-v4"]
body:
    - type: markdown
      attributes:
          value: |
              # 🧪 Editor V4 Discussion Form
              <br>

              👋 **Welcome, and thank you for helping shape the future of Elementor!**

              We're thrilled to have you here testing **Editor V4** — a major evolution of the Elementor Editor, rebuilt to improve performance, responsiveness, and your overall workflow.

              **This space is for sharing your thoughts, insights, and suggestions about Editor V4's experimental features. Your feedback is incredibly valuable and helps guide the direction of the product during its development.**

              Want to learn more about Editor V4? **[Visit our Editor V4 landing page](https://elemn.to/editor-v4)**, it will be updated regularly!
              <br>

              ## 🧭 Guidelines

              Before getting started, please review our **[Contribution Guidelines](https://github.com/nicholaszein/new-community-guidelines/blob/ba3181a0cc87ef6a3067a074f3ee7d5fc5fd58d3/.github/CONTRIBUTING.md)** and **[Code of Conduct](https://github.com/nicholaszein/new-community-guidelines/blob/ba3181a0cc87ef6a3067a074f3ee7d5fc5fd58d3/.github/CODE_OF_CONDUCT.md)**. These documents help us maintain a respectful, inclusive, and organized space for all contributors.
              <br>

              > [!IMPORTANT]
              > ### 🧪 This space is dedicated to discussing features in Editor V4.
              > 
              > If you're here to report a bug, please use the **[🐛 Editor V4 Bug Report Form](https://github.com/nicholaszein/new-community-guidelines/issues/new?template=editor-v4-bug.yml)**. 
              > 
              > Keep in mind that the **Editor V4** is still in early development — it may not include all existing features from Elementor V3 and is subject to change or instability.
              > 
              > For common questions, check the **[❔ Editor V4 FAQ](#)**.
              <br>

              ## 💡 Help Us Keep Editor V4 Discussions Organized

              - 🔍 **[Search for existing Editor V4 discussions](https://github.com/nicholaszein/new-community-guidelines/discussions/categories/editor-v4)**. <br>Someone may have already started a thread on the same topic. Add your thoughts there to keep conversations centralized.

              - ✒️ **Use a clear and descriptive title.** <br>A good title helps others quickly understand what your post is about, and participate on the discussion instead of creating a new one.

              - ☝️ **Stick to one topic per discussion thread.** <br>This makes it easier to track feedback and follow up on specific subjects.
    - type: textarea
      id: description
      validations:
          required: true
      attributes:
          label: "Description"
          description: "Please share your thoughts, feedback, or questions about the Editor V4 below."
          placeholder: "Start a discussion about the Editor V4..."
    - type: markdown
      attributes:
          value: |
              <br>
    - type: checkboxes
      id: final_agreement
      attributes:
          label: "Agreement"
          description: "By filling out this form, you confirm that you have read the guidelines outlined above, and you agree your discussion may be closed without warning if it doesn't meet them."
          options:
              - label: "I confirm I have read and followed the Editor V4 Discussion Form guidelines, and agree this discussion may be closed without warning."
                required: true
