labels: ["request"]
body:
    - type: markdown
      attributes:
          value: |
              ### 👋 Hello, welcome to Elementor Feature Requests!
              # ⚠️ BEFORE POSTING YOUR REQUEST READ THIS CAREFULLY
              ### 🚀 Please only use this form to request an Elementor plugin feature.
              🚩 Check our [Roadmap](https://elemn.to/roadmap) to learn what's in the pipeline.
              ### 🛟 Need Help, Guidance, Assistance, or Support? <ins>[Click here to get support](https://elemn.to/support-ticket)</ins>.
              ### 🐞 Need to Report a Bug? <ins>[Click here to Report a Bug](https://elemn.to/gh-new-bug-report)</ins>.
              <br>

              ### 😉 Follow these best practices to help save time
              - ✒️ **Write a Clear and Concise Title:** Summarize your title in a short sentence that can help identify your request at a glance.
              - ☝️ **One Request Per Thread:** If you have more than one request, please submit only **<ins>ONE REQUEST PER THREAD</ins>**. <br>Requests with more than one subject may be closed without action.
              <br>


              ### ✳️ Fill-in all required fields!
              - ❌ Requests lacking detail, or submitted for any other reason than to suggest new ideas, features, or enhancements for the Elementor plugin, may be closed without action.
              <br>

              ---
              <br>

              # THE REQUEST
              ### 📋 Prerequisites
              - 🔍 **Search Before Posting:** Before creating a new Feature Request, please [search for similar requests](https://elemn.to/gh-feature-requests) to prevent creating duplicates. 
              - If you're not sure your feature already exists, please check the [Elementor Features page](https://elemn.to/features).
    - type: checkboxes
      id: prerequisites
      attributes:
          label: "Prerequisites"
          options:
              - label: "I have searched for similar feature requests in both open and closed discussions and cannot find a an existing request."
                required: true
              - label: "I have verified that the feature is still missing in the latest stable versions of Elementor or Elementor Pro."
                required: true
    - type: markdown
      attributes:
          value: |
              <br>

              ### 💬 Provide a Detailed Description
              - Please explain in detail what problem your idea is going to solve. (Required)
              - Describe how you'd like a solution to be implemented. (Required)
              - Give examples of alternative solutions you've considered.
              - Add context to your suggestion by providing examples, screenshots, screen recordings, and related links and any additional information.
    - type: textarea
      id: the_problem
      validations:
          required: true
      attributes:
          label: "What problem is your feature request going to solve? Please describe."
          description: "Help everyone understand in detail what problems you are trying to solve."
          placeholder: "I'm always frustrated when ..."
    - type: textarea
      id: the_solution
      validations:
          required: true
      attributes:
          label: "Describe the solution you'd like."
          description: "Help everyone understand in a clear and concise description what you want to happen."
          placeholder: "It would be nice if ..."
    - type: textarea
      id: alternatives
      attributes:
          label: "Describe alternatives you've considered."
          description: "Give examples of any alternative solutions or features you've considered."
          placeholder: "It can also be solved by ..."
    - type: textarea
      id: additional_context
      attributes:
          label: "Additional context"
          description: "Add any other context, references, or illustrations about the feature request here."
          placeholder: "Here's an example of ..."
    - type: markdown
      attributes:
          value: |
              <br>

              ### 📃 Agreement
              - ⚠️ Please follow all the instructions indicated above, and fill in all the required fields with valid information. <br>We reserve the right to close requests that do not comply with these guidelines without any action.
    - type: checkboxes
      id: final_agreement
      attributes:
          label: "Agreement"
          options:
              - label: "I agree that my request may be closed without any action if it doesn't fulfill all the requirements."
                required: true
    - type: markdown
      attributes:
          value: |
              <br>

              ---
              ### Thank you for contributing and helping shape the future of Elementor! 🙏
