name: "🐞 Bug Report"
description: "Did you find a bug on Elementor and can reproduce it consistently? Report it here."
labels: ["status/awaiting_triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ BEFORE POSTING YOUR ISSUE
        ### 🐞 Please create GitHub issues only for Elementor Bug Reports. 
        #### ❌ GitHub issues should NOT BE USED FOR SUPPORT ❌.
        ❔ If you have questions, need guidance, help, or general support, please use one of the following channels:
        - [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
        - [Elementor Advanced Users](https://www.facebook.com/groups/elementoradvanced) A group on Facebook for more advanced users.
        - [Elementor Pioneers](https://www.facebook.com/groups/elementorpioneers) This Facebook group is for people who like to participate in new experiments.
        - [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
        - [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
        - [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

        💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/dashboard-support/) for details.

        ### 🙏 Follow these best practices to help save you time
        - 🔍 **Search Before Posting:** Before creating a new Bug Report, please search for similar issues to prevent creating duplicates.
        - 🆕 **Stay Up-to-date:** Make sure you are using the most recent and stable versions of [Elementor](https://wordpress.org/plugins/elementor/#developers), [Elementor Pro](https://elementor.com/pro/changelog/), [WordPress](https://wordpress.org/download/releases/), and your theme.
        - 🔬 **Isolate the problem:** Deactivate all of your plugins, and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.
        - 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's not an Elementor bug. In that case, use one of the support links above.
        - 🧩 **Contact 3rd-party Support:** If the issue happens with an Elementor add-on, extension, compatible plugin, or integrated theme, contact their support first. We do not provide support for 3rd-party software.
        - 1️⃣ **One Issue Per Thread:** If you are experiencing more than one bug, submit only **<ins>ONE ISSUE</ins>** per thread, so we can properly track them and reference them without any confusion.

        ## THE ISSUE
  - type: checkboxes
    id: prerequisites
    attributes:
      label: "Prerequisites"
      options:
        - label: "I have searched for similar issues in both open and closed tickets and cannot find a duplicate."
          required: true
        - label: "The issue still exists against the latest stable version of Elementor."
          required: true
  - type: dropdown
    id: bug_type
    attributes:
      label: "Type of Bug"
      description: "What type of bug are you reporting? Please select at least one option that is affected by the issue you're reporting (acceppts multiple options)."
      multiple: true
      options:
        - "I'm Not Sure"
        - "Accessibility"
        - "Compatibility"
        - "A Component"
        - "Content Management"
        - "Design"
        - "Developer-API"
        - "Dynamic Content"
        - "Experiment"
        - "Global Settings"
        - "Global Styles"
        - "Internationalization"
        - "Layout"
        - "Marketing"
        - "Multisite"
        - "Performance"
        - "Privacy"
        - "Product/Core"
        - "Product/Pro"
        - "Product/Dev-Edition"
        - "Responsiveness"
        - "SEO"
        - "Templates"
        - "Theme Builder"
        - "UI/UX"
        - "Workflow"
    validations:
      required: true
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "Description"
      description: "Describe the problem. What caused the issue? What did you expect to happen and what actually happened? Please be as descriptive as possible. Attach screenshots, screen recordings, and related links."
  - type: textarea
    id: steps_to_reproduce
    validations:
      required: true
    attributes:
      label: "Steps to reproduce"
      description: "List all the steps needed to reproduce the issue in detail, so we can replicate it ourselves on our own installation. Be thorough, we won't be able to reproduce it if you don't explain how."
      placeholder: "1) ... 2) ... 3) ..."
  - type: checkboxes
    id: isolating_the_problem
    attributes:
      label: "Isolating the problem"
      options:
        - label: "This bug happens with only Elementor plugin active (and Elementor Pro)."
        - label: "This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/))."
        - label: "I can reproduce this bug consistently using the steps above."
  - type: textarea
    id: system_info
    validations:
      required: true
    attributes:
      label: "System Info"
      description: "For faster debugging [copy your system environment](https://www.youtube.com/watch?v=tDXdynsnYuA) from your WordPress `Dashboard` > `Elementor` > `System info`, and paste it below.
      render: markdown
  - type: markdown
    attributes:
      value: |
        ℹ️ Please follow all the instructions indicated above, and fill all the required fields with valid information. We reserve the right to close issues that do not comply with these guidelines without any warning.
          
          
          
