name: "🐛 Report a Confirmed Bug in Editor V4"
description: "Report confirmed bugs in Editor V4's experimental features and help us improve the experience before the final release."
labels: ["status/awaiting_triage", "product/editor-v4"]
body:
    - type: markdown
      attributes:
          value: |
              # 🐛 Report a Confirmed Bug in Elementor Editor V4
              <br>

              👋 **Welcome, and thank you for helping shape the future of Elementor!**

              We're excited to introduce the **Editor V4** — a refreshed foundation for the Elementor Editor that improves performance, responsiveness, and workflow experience.

              Your feedback is incredibly valuable. Use this form to report bugs related to Editor V4's experimental features. Every report helps us create a better product before its full release.
              <br>

              ## 🧭 Guidelines

              Before getting started, please take a moment to review our **[Contribution Guidelines](https://github.com/nicholaszein/new-community-guidelines/blob/ba3181a0cc87ef6a3067a074f3ee7d5fc5fd58d3/.github/CONTRIBUTING.md)** and **[Code of Conduct](https://github.com/nicholaszein/new-community-guidelines/blob/ba3181a0cc87ef6a3067a074f3ee7d5fc5fd58d3/.github/CODE_OF_CONDUCT.md)**. These help us keep this space respectful, organized, and inclusive for everyone.
              <br>

              > [!IMPORTANT]
              > ### 🐛 This form is for reporting <ins>confirmed bugs in Editor V4</ins> experimental features only.
              > **We welcome your input, but please only use this form if you've already investigated and confirmed that the issue is caused specifically by Editor V4 features.**
              >
              > Keep in mind the **Editor V4 is a work in progress**, is subject to changes or instability during development, and should not be used on production sites.
              >
              > 🧪 For discussing and sharing feedback about the Editor V4, please go to the dedicated Discussion Category instead: **[Discuss the Editor V4](https://github.com/nicholaszein/new-community-guidelines/discussions/categories/editor-v4)**
              >
              > ❔ For frequent questions, check the **[Editor V4 FAQ](elemn.to/editor-v4-faq).**
              >
              > ⚠️ _**Reports that are unrelated to Editor V4 or missing required information may be closed without further review.**_
              <br>

              ### 📋 Requirements

              For a quick review and efficient resolution, please ensure your report meets the following requirements:

              - *️⃣ **All fields in this form are required** — no exceptions. <br>Incomplete issues will be closed without further action.

              - 🔍 **Search for similar issues before opening a new one.** <br>Avoid duplicates and save time by using the **[editor-v4](https://github.com/nicholaszein/new-community-guidelines/issues?q=is%3Aissue%20state%3Aopen%20label%3Aproduct%2Feditor-v4)** label to narrow your search.

              - 🗑️ **Clear all relevant cache layers.** <br>Confirm the issue is not being caused by stale or cached data. <br>Please clear server cache, site-level cache (including plugin-based cache), CDN cache, and your browser cache — in that order.

              - 🕵️ **Test with only Elementor, Elementor Pro, and the Hello Theme active.** <br>Temporarily disable all other plugins and themes. This step helps confirm that the issue is not being caused by a 3rd-party conflict. <br>👉 Reference: **[Troubleshooting the Editor](https://elemn.to/help-troubleshooting)**

              - 💾 **Copy and paste your complete Elementor System Info.** <br>This is not optional and helps us better reproduce and understand your issue. Reports without the full Elementor System Info will be closed. <br>👉 Learn how to copy it here: **[Share system information with Elementor](https://elemn.to/help-system-info)**

              - 🪪 **If you're a 3rd-party developer**, please introduce yourself. <br>Include your name, company, product name, and a way for us to contact you (such as an email address) if needed. <br>This helps us collaborate more effectively.

              - ☝️ **Only one issue per report.** <br>Please don't bundle multiple bugs in a single submission. This helps us track, reproduce, and fix each issue accurately.
              <br>

              ### 🎯 Scope

              To keep this repository focused and efficient, there are some types of reports that we are unable to handle here. These types of issues will be **closed without further action**. 

              - 🐞 **Issues unrelated to bugs in the Editor V4.** <br>If you're here to report issues with existing features of Elementor V3, please **[use our general 🐞 Bug Report form instead](https://github.com/nicholaszein/new-community-guidelines/issues/new?template=bug.yml)**.

              - 🛟 **Requests for personal support** <br>This includes help with setup, troubleshooting, or usage guidance. For that, please contact our **[official support channels](https://elemn.to/support-ticket)**.

              - 🧩 **Conflicts with 3rd-party plugins, themes, or services.** <br>We're only able to address issues related to Elementor and Elementor Pro directly. If the problem occurs when using a plugin, theme, or integration that is not officially supported by Elementor, please reach out to the 3rd-party provider for assistance.

              - 🚀 **Feature requests or suggestions.** <br>We love your ideas! But this form is only for confirmed bugs. Please use the dedicated Feature Request form instead. <br>See: **[Request a Feature](https://github.com/nicholaszein/new-community-guidelines/discussions/new?category=feature-request)**

              - 📚 **Questions about custom code or extending Elementor.** <br>We cannot provide assistance with writing or debugging custom code. If your goal is to extend Elementor, we recommend using our **[Developers Documentation](https://elemn.to/dev-docs)**.

              - 🛡️ **Security and vulnerability disclosures.** <br>We take security seriously. Please use our managed **[Bug Bounty Programs](https://elemn.to/bug-bounty)** to responsibly report security issues.

              - ☹️ **Complaints or offensive content.** <br>This is not the place to submit complaints about Elementor's products or services. We also do not tolerate offensive, discriminatory, or hostile remarks. Please keep discussions respectful as outlined in our **[Code of Conduct](https://github.com/nicholaszein/new-community-guidelines/blob/ba3181a0cc87ef6a3067a074f3ee7d5fc5fd58d3/.github/CODE_OF_CONDUCT.md)**.

              - ❌ **Incomplete, invalid, or out-of-scope reports.** <br>Issues without clear steps to reproduce, missing required fields, or unrelated to Elementor or Elementor Pro will be closed without further action.
              <br>

              ## 📝 Instructions

              To help us understand and resolve your issue, please follow these best practices:

              - ✒️ **Use a clear and descriptive title.** <br>A good title helps everyone quickly understand what the issue is about. Try to summarize the problem in a few words.

              - 💬 **Describe the issue in detail.** <br>Include as much context as you can. What happened? When did it start? What page or feature does it affect? <br>Feel free to attach screenshots or screen recordings — just drag and drop them into the text field when filling out the form.

              - 👣 **List all steps to reproduce the issue.** <br>Be specific! We need to follow the exact steps you took to reproduce the issue — ideally on a clean WordPress installation. <br>Reports without clear reproduction steps may be closed, as we cannot fix what we cannot replicate.

              - 🧠 **Explain what you expected to happen.** <br>Help us understand what you believe the correct or intended behavior should be. 
    - type: textarea
      id: description
      validations:
          required: true
      attributes:
          label: "Description"
          description: "Please describe the issue in detail and include as much context as possible. Feel free to attach screenshots or screen recordings — just drag and drop them into the field below."
          placeholder: "Examples: \nWhen I try to edit a Global Class in the Class Manager... \nThe Style Indicator in the {element_name} for the class... \nWhen I apply a Variable... n\..."
    - type: markdown
      attributes:
          value: |
              <br>
    - type: textarea
      id: steps_to_reproduce
      validations:
          required: true
      attributes:
          label: "Steps to reproduce"
          description: "List all steps to reproduce the issue. Be specific! We need to follow the exact steps you took to reproduce the issue, ideally on a clean WordPress installation."
          placeholder: "Example: \n1. In the WordPress Dashboard, go to... \n2. Create a Template... \n3. Drag & Drop the {widget_name} element... \n4. ..."
    - type: markdown
      attributes:
          value: |
              <br>
    - type: textarea
      id: expected_behavior
      validations:
          required: true
      attributes:
          label: "Expected behavior"
          description: "Explain what you expected to happen. Help us understand what you believe the correct or intended behavior should be. This helps us identify the root of the issue faster."
          placeholder: "Examples: \nWhen I apply a style to {widget_name} I expect it to... \nWhen I visit a page in the fontend, I expect... \nAccording to the Documentation in the Help Center... \n..."
    - type: markdown
      attributes:
          value: |
              <br>
    - type: textarea
      id: system_info
      validations:
          required: true
      attributes:
          label: "Elementor System Info"
          description: "This field is required and is not optional. Redact or remove sensitive information (like admin email, or root paths) if necessary. Keep other details, as these are vital for understanding your problem and recreating it correctly. To learn how to copy and paste the full report visit https://elemn.to/help-system-info."
          placeholder: "== Server Environment == \n== WordPress Environment == \n== Theme == \n== User == \n== Active Plugins == \n== Elements Usage == \n== Settings == \n== Features == \n== Integrations == \n== Elementor Experiments == \n== Log == \n== Elementor - Compatibility Tag == \n== Elementor Pro - Compatibility Tag =="
          render: txt
    - type: markdown
      attributes:
          value: |
              <br>
    - type: checkboxes
      id: final_agreement
      attributes:
          label: "Agreement"
          description: "By filling out this form, you confirm that you have read and followed the guidelines and instructions outlined above, and you agree that your issue may be closed without further action if it doesn't meet them."
          options:
              - label: "I confirm I have read and followed all the guidelines and instructions outlined in the Editor V4 Bug Report form."
                required: true
              - label: "I agree that my issue may be closed without further action if it doesn't meet all the requirements outlined in the Editor V4 Bug Report form."
                required: true
